application: hacktx19
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /
  static_files: bitcoin/index.html
  upload: bitcoin/index.html

- url: /crazy
  script: main.app

- url: /(.*)
  static_files: bitcoin/\1
  upload: bitcoin/(.*)



libraries:
- name: webapp2
  version: "2.5.2"
